paths:
  wiki_csv: data/wiki_age_gender_true_label.csv
  wiki_age_groups_csv: data/wiki_with_age_groups.csv
  fgnet_csv: data/cropped_fgnet.csv
  utk_csv: null

  models_dir: models
  outputs_dir: outputs

training:
  batch_size: 32
  image_size: 224
  epochs: 20
  learning_rate: 0.001

model:
  num_classes: 18
